---
- name: Deploiement de GitLab Runner avec Docker
  hosts: all
  become: true
  vars:
    runner_image: "debian:12"
    runner_description: "runner-{{ runner_tags | replace(',', '-') }}"
  tasks:
    - name: Creer le dossier de configuration du runner
      file:
        path: /srv/gitlab-runner/config
        state: directory
        recurse: yes

    - name: Enregistrer le GitLab Runner (via docker CLI)
      shell: |
        docker run --rm -v /srv/gitlab-runner/config:/etc/gitlab-runner \
          gitlab/gitlab-runner register \
          --non-interactive \
          --url "{{ gitlab_url }}" \
          --token "{{ registration_token }}" \
          --executor docker \
          --docker-image "{{ runner_image }}"



    - name: Attendre la creation du fichier config.toml
      wait_for:
        path: /srv/gitlab-runner/config/config.toml
        timeout: 30

    - name: Lancer le conteneur GitLab Runner
      docker_container:
        name: gitlab-runner
        image: gitlab/gitlab-runner
        state: started
        restart_policy: always
        volumes:
          - /srv/gitlab-runner/config:/etc/gitlab-runner
          - /var/run/docker.sock:/var/run/docker.sock
